# Generated by Django 5.2.11 on 2026-02-13 09:01

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True),
        ),
    ]
